import { User, Conversation, Message, ContactRequest, AdminStats, Notification } from '@/types';

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Ayesha Khan',
    age: 26,
    gender: 'female',
    city: 'Lahore',
    country: 'Pakistan',
    religion: 'Islam',
    sect: 'Sunni',
    education: 'MBBS - King Edward Medical University',
    profession: 'Doctor',
    height: "5'4\"",
    maritalStatus: 'Never Married',
    bio: 'A dedicated medical professional who values family, faith, and personal growth. Looking for a life partner who shares similar values and aspirations.',
    avatar: '',
    photos: [],
    isVerified: true,
    isPremium: true,
    isOnline: true,
    lastActive: '2 minutes ago',
    interests: ['Reading', 'Cooking', 'Travel', 'Charity Work'],
    familyValues: 'Traditional',
    lookingFor: 'A kind, educated, and family-oriented partner',
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    name: 'Ahmed Raza',
    age: 29,
    gender: 'male',
    city: 'Karachi',
    country: 'Pakistan',
    religion: 'Islam',
    sect: 'Sunni',
    education: 'MBA - IBA Karachi',
    profession: 'Software Engineer',
    height: "5'10\"",
    maritalStatus: 'Never Married',
    bio: 'Ambitious tech professional with a passion for innovation. Grounded in faith and family values, seeking a partner to build a meaningful life together.',
    avatar: '',
    photos: [],
    isVerified: true,
    isPremium: false,
    isOnline: false,
    lastActive: '1 hour ago',
    interests: ['Technology', 'Cricket', 'Hiking', 'Photography'],
    familyValues: 'Moderate',
    lookingFor: 'Someone who is educated, understanding, and supportive',
    createdAt: '2024-02-10',
  },
  {
    id: '3',
    name: 'Fatima Ali',
    age: 24,
    gender: 'female',
    city: 'Islamabad',
    country: 'Pakistan',
    religion: 'Islam',
    sect: 'Sunni',
    education: 'MSc Computer Science - NUST',
    profession: 'UX Designer',
    height: "5'3\"",
    maritalStatus: 'Never Married',
    bio: 'Creative professional with a love for art and design. I believe in balancing career aspirations with spiritual growth and family bonds.',
    avatar: '',
    photos: [],
    isVerified: true,
    isPremium: true,
    isOnline: true,
    lastActive: '5 minutes ago',
    interests: ['Art', 'Design', 'Yoga', 'Calligraphy'],
    familyValues: 'Traditional',
    lookingFor: 'A compassionate partner with strong moral values',
    createdAt: '2024-03-01',
  },
  {
    id: '4',
    name: 'Hassan Malik',
    age: 31,
    gender: 'male',
    city: 'Rawalpindi',
    country: 'Pakistan',
    religion: 'Islam',
    sect: 'Sunni',
    education: 'PhD Engineering - UET Lahore',
    profession: 'Civil Engineer',
    height: "5'11\"",
    maritalStatus: 'Never Married',
    bio: 'Hardworking engineer who believes in building strong foundations — both in structures and relationships. Family-oriented and practice my faith daily.',
    avatar: '',
    photos: [],
    isVerified: true,
    isPremium: false,
    isOnline: false,
    lastActive: '3 hours ago',
    interests: ['Architecture', 'Swimming', 'Reading', 'Gardening'],
    familyValues: 'Traditional',
    lookingFor: 'A caring and educated life partner',
    createdAt: '2024-01-20',
  },
  {
    id: '5',
    name: 'Zainab Hussain',
    age: 27,
    gender: 'female',
    city: 'Multan',
    country: 'Pakistan',
    religion: 'Islam',
    sect: 'Shia',
    education: 'LLB - Punjab University',
    profession: 'Lawyer',
    height: "5'5\"",
    maritalStatus: 'Never Married',
    bio: 'An advocate for justice in the courtroom and kindness at home. Seeking a partner who values intellect, empathy, and shared spiritual goals.',
    avatar: '',
    photos: [],
    isVerified: false,
    isPremium: false,
    isOnline: true,
    lastActive: '10 minutes ago',
    interests: ['Law', 'Debate', 'Horse Riding', 'Poetry'],
    familyValues: 'Moderate',
    lookingFor: 'An honest, respectful, and ambitious partner',
    createdAt: '2024-04-05',
  },
  {
    id: '6',
    name: 'Omar Farooq',
    age: 33,
    gender: 'male',
    city: 'Faisalabad',
    country: 'Pakistan',
    religion: 'Islam',
    sect: 'Sunni',
    education: 'BBA - LUMS',
    profession: 'Business Owner',
    height: "6'0\"",
    maritalStatus: 'Divorced',
    bio: 'Experienced businessman and devoted father. Looking for a second chance at a loving partnership built on trust, respect, and shared faith.',
    avatar: '',
    photos: [],
    isVerified: true,
    isPremium: true,
    isOnline: false,
    lastActive: '1 day ago',
    interests: ['Business', 'Travel', 'Fishing', 'Volunteering'],
    familyValues: 'Traditional',
    lookingFor: 'A kind-hearted and understanding partner',
    createdAt: '2024-02-28',
  },
  {
    id: '7',
    name: 'Mariam Qureshi',
    age: 25,
    gender: 'female',
    city: 'Peshawar',
    country: 'Pakistan',
    religion: 'Islam',
    sect: 'Sunni',
    education: 'BDS - Khyber Medical College',
    profession: 'Dentist',
    height: "5'2\"",
    maritalStatus: 'Never Married',
    bio: 'Friendly and outgoing dental professional. I value family above everything and am looking for someone who shares my enthusiasm for life and faith.',
    avatar: '',
    photos: [],
    isVerified: true,
    isPremium: false,
    isOnline: true,
    lastActive: 'Just now',
    interests: ['Cooking', 'Shopping', 'Skincare', 'Charity'],
    familyValues: 'Traditional',
    lookingFor: 'A practicing Muslim with good family values',
    createdAt: '2024-03-15',
  },
  {
    id: '8',
    name: 'Bilal Ahmad',
    age: 28,
    gender: 'male',
    city: 'Lahore',
    country: 'Pakistan',
    religion: 'Islam',
    sect: 'Sunni',
    education: 'MS Data Science - FAST',
    profession: 'Data Scientist',
    height: "5'9\"",
    maritalStatus: 'Never Married',
    bio: 'Data-driven by day, faith-driven always. I enjoy solving complex problems and believe the best partnership is one where both people grow together.',
    avatar: '',
    photos: [],
    isVerified: true,
    isPremium: true,
    isOnline: false,
    lastActive: '30 minutes ago',
    interests: ['AI', 'Gaming', 'Fitness', 'Astronomy'],
    familyValues: 'Moderate',
    lookingFor: 'An intelligent and supportive life partner',
    createdAt: '2024-04-10',
  },
];

export const mockConversations: Conversation[] = [
  {
    id: 'conv-1',
    user: mockUsers[0],
    lastMessage: {
      id: 'msg-1',
      senderId: '1',
      receiverId: 'me',
      content: 'Assalamu Alaikum! Thank you for your interest.',
      timestamp: '2024-04-15T10:30:00Z',
      read: false,
    },
    unreadCount: 2,
  },
  {
    id: 'conv-2',
    user: mockUsers[2],
    lastMessage: {
      id: 'msg-2',
      senderId: 'me',
      receiverId: '3',
      content: 'I would love to know more about your family.',
      timestamp: '2024-04-14T15:45:00Z',
      read: true,
    },
    unreadCount: 0,
  },
  {
    id: 'conv-3',
    user: mockUsers[4],
    lastMessage: {
      id: 'msg-3',
      senderId: '5',
      receiverId: 'me',
      content: 'That sounds wonderful! When would you like to chat?',
      timestamp: '2024-04-13T09:20:00Z',
      read: false,
    },
    unreadCount: 1,
  },
];

export const mockContactRequests: ContactRequest[] = [
  {
    id: 'req-1',
    fromUser: mockUsers[1],
    toUserId: 'me',
    status: 'pending',
    sentAt: '2024-04-15T08:00:00Z',
  },
  {
    id: 'req-2',
    fromUser: mockUsers[3],
    toUserId: 'me',
    status: 'pending',
    sentAt: '2024-04-14T12:00:00Z',
  },
  {
    id: 'req-3',
    fromUser: mockUsers[5],
    toUserId: 'me',
    status: 'accepted',
    sentAt: '2024-04-13T06:00:00Z',
  },
];

export const mockAdminStats: AdminStats = {
  totalUsers: 12847,
  activeUsers: 3256,
  premiumUsers: 1089,
  pendingVerifications: 47,
  totalMessages: 89432,
  totalMatches: 2341,
  newUsersToday: 156,
  revenue: 45670,
};

export const mockNotifications: Notification[] = [
  {
    id: 'notif-1',
    type: 'interest',
    title: 'New Interest Received',
    description: 'Ahmed Raza has expressed interest in your profile',
    read: false,
    createdAt: '2024-04-15T10:00:00Z',
  },
  {
    id: 'notif-2',
    type: 'message',
    title: 'New Message',
    description: 'Ayesha Khan sent you a message',
    read: false,
    createdAt: '2024-04-15T09:30:00Z',
  },
  {
    id: 'notif-3',
    type: 'view',
    title: 'Profile Viewed',
    description: 'Your profile was viewed by 5 people today',
    read: true,
    createdAt: '2024-04-14T18:00:00Z',
  },
  {
    id: 'notif-4',
    type: 'match',
    title: 'New Match!',
    description: 'You and Fatima Ali are a match!',
    read: true,
    createdAt: '2024-04-14T14:00:00Z',
  },
  {
    id: 'notif-5',
    type: 'system',
    title: 'Profile Verified',
    description: 'Your profile has been verified by our team',
    read: true,
    createdAt: '2024-04-13T10:00:00Z',
  },
];
